version: '3.3'

services: 
  db:
    image: postgres
    env_file: 
      - .env
    volumes: 
      - db_data:/var/lib/postgresql/data
  
  web:
    build: 
      context: .
    env_file: 
      - .env
    ports: 
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on: 
      - db

volumes:
  db_data: