
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 
development:
  <<: *default
  database: the_best_app_development
test:
  <<: *default
  database: the_best_app_test
production:
  <<: *default
  database: the_best_app_production
  username: the_best_app
  password: <%= ENV['THE_BEST_APP_DATABASE_PASSWORD'] %>
